#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                  Giangi Sacco
#                        NASA Jet Propulsion Laboratory
#                      California Institute of Technology
#                        (C) 2009  All Rights Reserved
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#!/usr/bin/env python


import os
import sys
Import('envdefaults')
package = os.path.join('defaults', 'logging')
envdefaultslogging = envdefaults.Clone()
envdefaultslogging['PACKAGE'] = package

install = os.path.join(envdefaultslogging['DEFAULTS_SCONS_INSTALL'], package)

listFiles = ['__init__.py', 'logging.conf']
envdefaultslogging.Install(install,listFiles)
envdefaultslogging.Alias('install',install)
Export('envdefaultslogging')
