#! /usr/bin/env python
#
# Author: Kosal Khun
# Copyright 2013
#
# adapted from InsarProc/SConscript

import os

Import('envisceobj')
package = envisceobj['PACKAGE']
project = 'IsceProc'

install = os.path.join(envisceobj['PRJ_SCONS_INSTALL'],package,project)

listFiles = ['__init__.py', 'Factories.py', 'IsceProc.py', 'runCoherence.py',
             'runEstimateHeights.py', 'runEstimateHeights_peg.py', 'runFilter.py',
             'runFormSLC.py', 'runFormSLCisce.py', 'runFormSLCTSX.py','runGeocode.py',
             'runGrass.py', 'runMocompbaseline.py', 'runOffoutliers.py',
             'runOrbit2sch.py', 'runPrepareResamps.py', 'runPreprocessor.py',
             'runPulseTiming.py', 'runResamp_image.py', 'runResamp_only.py',
             'runResamp.py', 'runOffsetprf.py', 'runOffsetprf_ampcor.py',
             'runOffsetprf_nstage.py', 'runRgoffset.py', 'runRgoffset_none.py',
             'runRgoffset_ampcor.py', 'runRgoffset_nstage.py',
             'runSetmocomppath.py', 'runSetmocomppathFromFrame.py',
             'runShadecpx2rg.py', 'runTopo.py', 'runCorrect.py',
             'runUpdatePreprocInfo.py', 'extractInfo.py', 'createDem.py',
             'runISSI.py', 'runCrossmul.py', 'runUnwrapGrass.py',
             'runUnwrapIcu.py', 'runUnwrapSnaphu.py'
             ]

envisceobj.Install(install,listFiles)
envisceobj.Alias('install',install)
