#!/usr/bin/env python
#
# Author: Giangi Sacco
# Copyright 2010
#

import os

Import('envstdproc')
package = 'rectify'
envrectify = envstdproc.Clone()
envrectify['PACKAGE'] = envstdproc['PACKAGE'] + '/' + package
install = envstdproc['PRJ_SCONS_INSTALL'] + '/' + envrectify['PACKAGE']
initFile = '__init__.py'
if not os.path.exists(initFile):
        fout = open(initFile,"w")
        fout.write("#!/usr/bin/env python")
        fout.close()

listFiles = [initFile]
envrectify.Install(install,listFiles)
envrectify.Alias('install',install)
Export('envrectify')
geocode = 'geocode/SConscript'
SConscript(geocode)
