#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                  Giangi Sacco
#                        NASA Jet Propulsion Laboratory
#                      California Institute of Technology
#                        (C) 2009  All Rights Reserved
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#!/usr/bin/env python
import os
Import('envStdOEL')
build = envStdOEL['PRJ_LIB_DIR']
listFiles = ['StdOEL.cpp','StdOELF.cpp','FileWriter.cpp','ScreenWriter.cpp','WriterFactory.cpp']
libStdOEL = envStdOEL.Library(target = 'StdOEL', source = listFiles)
envStdOEL.Install(build,libStdOEL)
envStdOEL.Alias('build',build)
