#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2012 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envUtil')
install = envUtil['PRJ_LIB_DIR'] 
#envUtil.AppendUnique(LINKFLAGS = '-i4')
envUtil.AppendUnique(CPPDEFINES = ['HAVE_CONFIG_H','HAVE_FFTW=1'])
listFiles = ['sfftw_import.c','args_roi.F','besseldiffs.F','bilinear.F','cfft1d_jpl.F','cfft2d.F','cffts.F', \
             'convert_sch_to_xyz.F','convert_schdot_to_xyzdot.F','cross.F','curvature.F', \
             'derampc.F','dop.F','dot.F','enubasis.F','fc.F','fourn.F','fournnr.F', \
             'getangs.F','gettcn_tcvec.F','hunt.F','inter_motion.F','interp.F','intpcoefnorm.F', \
             'latlon.F','lfit.F','lincomb.F','lookvec.F','matmat.F','matvec.F','norm.F', \
             'orrmread1.F','polint.F','radar_to_xyz.F','schbasis.F','svd.F','svdvecfit.F', \
             'svdvecfit9.F','tranmat.F','unitvec.F','utmtoll.F','zbrent.F','PowerOfTwo.cc', \
             'fftw3stub.c','io.c','second.c','fortranUtils.f90','intp_coef.f90','linalg.f90', \
             'lsq.f90','quadfit.f90','uniform_interp.f90','akima_reg.F','spline.f']
lib = envUtil.Library(target = 'utilLib', source = listFiles)
envUtil.Install(install,lib)
envUtil.Alias('install',install)
