#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2011 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('env')
Import('envapplications')
Import('envcomponents')
envcontrib = env.Clone()
package = 'contrib'
envcontrib['PACKAGE'] = os.path.join(envcomponents['PACKAGE'],package)
envcontrib['INSTALL_COMPS'] = os.path.join(envcomponents['INSTALL_PATH'],package)
envcontrib['INSTALL_APPS'] = envapplications['INSTALL_PATH']
envcontrib['INSTALL_PATH'] = envcontrib['INSTALL_COMPS']
install = envcontrib['INSTALL_PATH']

initFile = '__init__.py'
if not os.path.exists(initFile):
	fout = open(initFile,"w")
	fout.write("#!/usr/bin/env python")
	fout.close()

listFiles = [initFile]
envcontrib.Install(install,listFiles)
envcontrib.Alias('install',install)
Export('envcontrib')

issi = os.path.join('issi','SConscript')
SConscript(issi)
snaphu = os.path.join('Snaphu','SConscript')
SConscript(snaphu)
demUtils = os.path.join('demUtils','SConscript')
SConscript(demUtils)
frameUtils = os.path.join('frameUtils','SConscript')
SConscript(frameUtils)
unwUtils = os.path.join('UnwrapComp','SConscript')
SConscript(unwUtils)
downsample_unwrapper = os.path.join('downsample_unwrapper','SConscript')
SConscript(downsample_unwrapper)

if 'MOTIFLIBPATH' in envcontrib.Dictionary():
    mdx = os.path.join('mdx','SConscript')
    SConscript(mdx)

rfi = os.path.join('rfi', 'SConscript')
SConscript(rfi)

SConscript('PyCuAmpcor/SConscript')
SConscript('splitSpectrum/SConscript')
SConscript('alos2proc/SConscript')

if os.path.exists('geo_autoRIFT'):
    SConscript('geo_autoRIFT/SConscript')
