#!/usr/bin/env python

#Cunren Liang, 2015-2018

import os

Import('envcontrib')
envalos2proc = envcontrib.Clone()
package = envcontrib['PACKAGE']
project = 'alos2proc'
Export('envalos2proc')


includeScons = os.path.join('include','SConscript')
SConscript(includeScons)

srcScons = os.path.join('src','SConscript')
varDir = os.path.join(envalos2proc['PRJ_SCONS_BUILD'],package,project,'src')
SConscript(srcScons, variant_dir = varDir)


install = os.path.join(envcontrib['PRJ_SCONS_INSTALL'],package,project)
listFiles = ['__init__.py','alos2proc.py']
envcontrib.Install(install,listFiles)
envcontrib.Alias('install',install)

