#!/usr/bin/env python

import os

Import('envFilter')
package = envFilter['PACKAGE']
project = 'Filter'
build = os.path.join(envFilter['PRJ_SCONS_BUILD'],package,project,'include')
envFilter.AppendUnique(CPPPATH = [build])
listFiles = ['filtermodule.h','header.h','Filter.hh','MeanFilter.hh','GaussianFilter.hh','Image.hh']
envFilter.Install(build,listFiles)
envFilter.Alias('install',build)
