#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                  Giangi Sacco
#                        NASA Jet Propulsion Laboratory
#                      California Institute of Technology
#                        (C) 2009  All Rights Reserved
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#!/usr/bin/env python
import os

Import('envStdOE')
package = envStdOE['PACKAGE']
project = envStdOE['PROJECT']
envStdOE.AppendUnique(LIBPATH = envStdOE['PRJ_LIB_DIR'])
install = envStdOE['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
libList = ['StdOE']
envStdOE.PrependUnique(LIBS = libList)
module = envStdOE.LoadableModule(target = 'StdOE.abi3.so', source = 'StdOEmodule.cpp') 
envStdOE.Install(install,module)
envStdOE.Alias('install',install)
