#
# Author: Eric Gurrola
# Copyright 2016

#Pass the environment down
Import('envtest_isceobj')
envtest_Planet = envtest_isceobj.Clone()

#import the test package
import test
#Print entering banner
test.print_entering_banner('isceobj/Planet')
#List the tests to be run in the current directory
testFiles = ['test_ellipsoid.py']
#Run the tests
test.run_tests_and_print(testFiles)
#Cleanup files created in this test
cleanup_list = ['isce.log']
test.cleanup(cleanup_list)
