#!/usr/bin/env python
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Author: Yang Lei
# Copyright 2019, by the California Institute of Technology. ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer at the California Institute of Technology.
#
# This software may be subject to U.S. export control laws. By accepting this software, the user agrees to comply with all applicable U.S.
# export laws and regulations. User has the responsibility to obtain export licenses, or other export authority as may be required before 
# exporting such information to foreign countries or providing access to foreign persons.
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


import os

Import('envautorift')
package = envautorift['PACKAGE']
project = envautorift['PROJECT']
install = envautorift['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envautorift['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
#libList = ['gomp','autorift','combinedLib','gdal']
#libList = ['gomp','combinedLib','gdal','opencv_core','opencv_highgui','opencv_imgproc']
libList = ['opencv_core','opencv_highgui','opencv_imgproc']
envautorift.PrependUnique(LIBS = libList)
module = envautorift.LoadableModule(target = 'autoriftcore.so', source = 'autoriftcoremodule.cpp')
envautorift.Install(install,module)
envautorift.Alias('install',install)
envautorift.Install(build,module)
envautorift.Alias('build',build)
