#!/usr/bin/env python
import os
import sys

Import('envcontrib')
envalos2procF = envcontrib.Clone()
package = envalos2procF['PACKAGE'] # 'contrib'
project = 'alos2proc_f'
envalos2procF['PROJECT'] = project
Export('envalos2procF')

SConscript('src/SConscript', variant_dir = os.path.join(envalos2procF['PRJ_SCONS_BUILD'],package,project,'src'))
SConscript('include/SConscript')

if envalos2procF['CYTHON3']:
    print("cython3 found.")
    SConscript('pyx/SConscript')
else:
    print("cython3 is required to build the alos2proc_f bindings.")
    print("The alos2proc_f bindings will not be built. Please install cython3.")

install_main = os.path.join(envalos2procF['PRJ_SCONS_INSTALL'], package, project)
envalos2procF.Install(install_main,'__init__.py')
