#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2010 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envstdproc')
package = 'stdproc'
envstdproc1 = envstdproc.Clone()
envstdproc1['PACKAGE'] = envstdproc['PACKAGE'] + '/' + package
install = envstdproc1['PRJ_SCONS_INSTALL'] + '/' + envstdproc1['PACKAGE']
initFile = '__init__.py'
if not os.path.exists(initFile):
	fout = open(initFile,"w")
	fout.write("#!/usr/bin/env python")
	fout.close()
helpList,installHelp = envstdproc1['HELP_BUILDER'](envstdproc1,'__init__.py',install)
envstdproc1.Install(installHelp,helpList)
envstdproc1.Alias('install',installHelp)
listFiles = [initFile]
envstdproc1.Install(install,listFiles)
envstdproc1.Alias('install',install)
Export('envstdproc1')
formslc = 'formslc/SConscript'
SConscript(formslc)
formslcLib = 'formslcLib/SConscript'
SConscript(formslcLib)
#resampTest = 'resampTest/SConscript'
#SConscript(resampTest)
resamp = 'resamp/SConscript'
SConscript(resamp)
resampLib = 'resampLib/SConscript'
SConscript(resampLib)
resamp_image = 'resamp_image/SConscript'
SConscript(resamp_image)
resamp_amps = 'resamp_amps/SConscript'
SConscript(resamp_amps)
resamp_only = 'resamp_only/SConscript'
SConscript(resamp_only)
resamp_slc = 'resamp_slc/SConscript'
SConscript(resamp_slc)
topo = 'topo/SConscript'
SConscript(topo)
correct = 'correct/SConscript'
SConscript(correct)
mocompTSX = 'mocompTSX/SConscript'
SConscript(mocompTSX)
crossmul = 'crossmul/SConscript'
SConscript(crossmul)
estamb = 'estamb/SConscript'
SConscript(estamb)
offsetpoly= 'offsetpoly/SConscript'
SConscript(offsetpoly)
