#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2010 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envstdproc')
package = 'alosreformat'
envalosreformat = envstdproc.Clone()
envalosreformat['PACKAGE'] = os.path.join(envstdproc['PACKAGE'],package)

install = os.path.join(envstdproc['PRJ_SCONS_INSTALL'],envalosreformat['PACKAGE'])
initFile = '__init__.py'
listFiles = [initFile]
envalosreformat.Install(install,listFiles)
envalosreformat.Alias('install',install)
Export('envalosreformat')

#do the include first sicnce it adds the CPPPATH to envalosreformat and re-exports it so the others can share it
ALOS_include = os.path.join('include','SConscript')
SConscript(ALOS_include)

ALOS_lib = os.path.join('ALOS_lib','SConscript')
SConscript(ALOS_lib)

ALOS_fbs2fbd = os.path.join('ALOS_fbs2fbd','SConscript')
SConscript(ALOS_fbs2fbd)

ALOS_fbd2fbs = os.path.join('ALOS_fbd2fbs','SConscript')
SConscript(ALOS_fbd2fbs)

