#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                  Giangi Sacco
#                        NASA Jet Propulsion Laboratory
#                      California Institute of Technology
#                        (C) 2009-2010  All Rights Reserved
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#!/usr/bin/env python
import os

Import('enviscesys')
envDateTimeUtil = enviscesys.Clone()
package = envDateTimeUtil['PACKAGE']
project = 'DateTimeUtil'
envDateTimeUtil['PROJECT'] = project
install = envDateTimeUtil['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
listFiles = ['DateTimeUtil.py','__init__.py']
envDateTimeUtil.Install(install,listFiles)
envDateTimeUtil.Alias('install',install)
