import os

Import('envSnaphu')
install = envSnaphu['PRJ_LIB_DIR'] 
listFiles = ['snaphu.c','snaphu_cost.c','snaphu_cs2.c','snaphu_io.c','snaphu_solver.c','snaphu_tile.c','snaphu_util.c']
lib = envSnaphu.Library(target = 'snaphu', source = listFiles)
envSnaphu.Install(install,lib)
envSnaphu.Alias('install',install)
