#!/usr/bin/env python
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Author: Piyush Agram
# Copyright 2019, by the California Institute of Technology. ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer at the California Institute of Technology.
#
# This software may be subject to U.S. export control laws. By accepting this software, the user agrees to comply with all applicable U.S.
# export laws and regulations. User has the responsibility to obtain export licenses, or other export authority as may be required before 
# exporting such information to foreign countries or providing access to foreign persons.
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


import os

Import('envgeogrid')
package = envgeogrid['PACKAGE']
project = envgeogrid['PROJECT']
install = envgeogrid['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envgeogrid['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
libList = ['gomp','geogrid','combinedLib','gdal']
envgeogrid.PrependUnique(LIBS = libList)
module = envgeogrid.LoadableModule(target = 'geogrid.abi3.so', source = 'geogridmodule.cpp') 
envgeogrid.Install(install,module)
envgeogrid.Alias('install',install)
envgeogrid.Install(build,module)
envgeogrid.Alias('build',build)
