#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                  Giangi Sacco
#                        NASA Jet Propulsion Laboratory
#                      California Institute of Technology
#                        (C) 2009  All Rights Reserved
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#!/usr/bin/env python
import os

Import('enviscesys')
envTraits = enviscesys.Clone()
project = 'Traits'
envTraits['PROJECT'] = project
package = envTraits['PACKAGE']
Export('envTraits')
install = os.path.join(envTraits['PRJ_SCONS_INSTALL'],package,project)

initFile = '__init__.py'
listFiles = ['Datetime.py', initFile]
envTraits.Install(install,listFiles)
envTraits.Alias('install',install)
