#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2010 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Walter Szeliga
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#!/usr/bin/env python

import os

import fnmatch
Import('envSensor')
envSensordb = envSensor.Clone()
package = 'db'
envSensordb['SENSORDB_SCONS_INSTALL'] = os.path.join(
    envSensor['SENSOR_SCONS_INSTALL'], package)

install = envSensordb['SENSORDB_SCONS_INSTALL']

listFiles = ['__init__.py']
envSensordb.Install(install,listFiles)
envSensordb.Alias('install',install)
Export('envSensordb')

SConscript(os.path.join('alos', 'SConscript'))
SConscript(os.path.join('ers', 'SConscript'))
SConscript(os.path.join('jers', 'SConscript'))
SConscript(os.path.join('radarsat', 'SConscript'))
SConscript(os.path.join('risat', 'SConscript'))
SConscript(os.path.join('radarsat_slc', 'SConscript'))
SConscript(os.path.join('risat_slc', 'SConscript'))
SConscript(os.path.join('alos2_slc', 'SConscript'))
SConscript(os.path.join('ers_slc', 'SConscript'))
SConscript(os.path.join('alos_slc', 'SConscript'))
