#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                  Giangi Sacco
#                        NASA Jet Propulsion Laboratory
#                      California Institute of Technology
#                        (C) 2009-2010  All Rights Reserved
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#!/usr/bin/env python
import os

Import('enviscesys')
envImageUtil = enviscesys.Clone()
package = envImageUtil['PACKAGE']
project = 'ImageUtil'
envImageUtil['PROJECT'] = project
install = envImageUtil['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
listFiles = ['ImageUtil.py','__init__.py']
envImageUtil.Install(install,listFiles)
envImageUtil.Alias('install',install)
