#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                 Walter Szeliga
#                        NASA Jet Propulsion Laboratory
#                      California Institute of Technology
#                        (c) 2010  All Rights Reserved
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#!/usr/bin/env python
import os

Import('envSensor')
envTOPS = envSensor.Clone()
project = 'TOPS'
package = envTOPS['PACKAGE']
envTOPS['PROJECT'] = project
envTOPS['SENSOR_SCONS_INSTALL'] = os.path.join(
    envTOPS['PRJ_SCONS_INSTALL'], package, 'Sensor',project)
install = envTOPS['SENSOR_SCONS_INSTALL']

listFiles = ['__init__.py','BurstSLC.py','TOPSSwathSLCProduct.py','TOPSSLCProduct.py','Sentinel1.py']

helpList,installHelp = envTOPS['HELP_BUILDER'](envTOPS,'__init__.py',install)

envTOPS.Install(installHelp,helpList)
envTOPS.Alias('install',installHelp)

envTOPS.Install(install,listFiles)
envTOPS.Alias('install',install)
