#!/usr/bin/env python

import os

Import('envzenith2los')
package = envzenith2los['PACKAGE']
project = 'zenith2los'
build = os.path.join(envzenith2los['PRJ_SCONS_BUILD'],package,project,'include')
envzenith2los.AppendUnique(CPPPATH = [build])
listFiles = ['zenith2losmodule.h','zenith2los.h']
envzenith2los.Install(build,listFiles)
envzenith2los.Alias('install',build)
