#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2011 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envcontrib')
envmdx = envcontrib.Clone()

OPTIMIZATION = ''
envmdx.Replace(FORTRANFLAGS = str(envmdx['FORTRANFLAGS']).replace(str(envmdx['COMPILER_OPTIMIZATION']),OPTIMIZATION).split())
envmdx.Replace(CCFLAGS = str(envmdx['CCFLAGS']).replace(str(envmdx['COMPILER_OPTIMIZATION']),OPTIMIZATION).split())

envmdx['PACKAGE'] = envcontrib['PACKAGE']
envmdx['INSTALL_COMPS'] = envcontrib['INSTALL_COMPS']
envmdx['INSTALL_APPS'] = envcontrib['INSTALL_APPS']
package = envmdx['PACKAGE']
project = 'mdx'
build = os.path.join(envmdx['PRJ_SCONS_BUILD'],package,project)
envmdx['PROJECT'] = project
Export('envmdx')

src = os.path.join('src','SConscript')
SConscript(src,variant_dir=os.path.join(build,'src'))
