#!/usr/bin/env python

import os

Import('envalos2proc')

install = os.path.join(envalos2proc['PRJ_SCONS_INSTALL'], envalos2proc['PACKAGE'], 'alos2proc')
listFiles = ['lib_array.c', 'lib_cpx.c', 'lib_file.c', 'lib_func.c', 'mbf.c', 'rg_filter.c', 'resamp.c', 'mosaicsubswath.c', 'look.c', 'extract_burst.c']

# -shared
# -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -lm
# -lfftw3f_threads -lfftw3f -lpthread -fopenmp -O3 

#envalos2proc.Append(CFLAGS=['-D_LARGEFILE64_SOURCE', '-D_FILE_OFFSET_BITS=64', '-lm', '-shared', '-fopenmp', '-O3'])
#envalos2proc.Append(LIBS=['fftw3f', 'fftw3f_threads', 'pthread'])

lib = envalos2proc.LoadableModule(target = 'libalos2proc.so', source = listFiles, parse_flags='-fopenmp')
envalos2proc.Install(install,lib)
envalos2proc.Alias('install',install)




