#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2010 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#!/usr/bin/env python

import os

Import('envisceobj')
envImageFilter = envisceobj.Clone()
project = 'ImageFilter'
envImageFilter['PROJECT'] = project
package = envImageFilter['PACKAGE']
Export('envImageFilter')
install = os.path.join(envImageFilter['PRJ_SCONS_INSTALL'], package, project)

listFiles = ['__init__.py', 'ImageFilter.py', 'FilterFactory.py',
    'BandExtractor.py', 'ComplexExtractor.py']

envImageFilter.Install(install,listFiles)
envImageFilter.Alias('install',install)

includeScons = os.path.join('include', 'SConscript')
SConscript(includeScons)

bindingsScons = os.path.join('bindings', 'SConscript')
SConscript(bindingsScons, variant_dir = os.path.join(
    envImageFilter['PRJ_SCONS_BUILD'], package, project, 'bindings'))

srcScons = os.path.join('src', 'SConscript')
SConscript(srcScons, variant_dir = os.path.join(
    envImageFilter['PRJ_SCONS_BUILD'], package, project, 'src'))
