#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2012 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envEstimateOffsets')
package = envEstimateOffsets['PACKAGE']
project = envEstimateOffsets['PROJECT']
install = envEstimateOffsets['PRJ_SCONS_INSTALL'] + '/' + package 
build = envEstimateOffsets['PRJ_SCONS_BUILD'] + '/' + package 
libList = ['estimateoffsets','DataAccessor','InterleavedAccessor','utilLib','fftw3f']
envEstimateOffsets.PrependUnique(LIBS = libList)
module = envEstimateOffsets.LoadableModule(target = 'estimateoffsets.abi3.so', source = 'estimateoffsetsmodule.cpp') 
envEstimateOffsets.Install(install,module)
envEstimateOffsets.Alias('install',install)
envEstimateOffsets.Install(build,module)
envEstimateOffsets.Alias('build',build)
