#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2014 California Institute of Technology. ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# United States Government Sponsorship acknowledged. This software is subject to
# U.S. export control laws and regulations and has been classified as 'EAR99 NLR'
# (No [Export] License Required except when exporting to an embargoed country,
# end user, or in support of a prohibited end use). By downloading this software,
# the user agrees to comply with all applicable U.S. export laws and regulations.
# The user has the responsibility to obtain export licenses, or other export
# authority as may be required before exporting this software to any 'EAR99'
# embargoed foreign country or citizen of those countries.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


import os
import sys
Import('envcomponents')
package = 'components/isceobj'
envisceobj = envcomponents.Clone()
envisceobj['PACKAGE'] = package
install = envisceobj['PRJ_SCONS_INSTALL'] + '/' + package
initFile = '__init__.py'
if not os.path.exists(initFile):
        fout = open(initFile,"w")
        fout.write("#!/usr/bin/env python")
        fout.close()

listFiles = [initFile]
envisceobj.Install(install,listFiles)
envisceobj.Alias('install',install)
Export('envisceobj')
SConscript('LineAccessor/SConscript')
SConscript('Image/SConscript')
SConscript('Platform/SConscript')
SConscript('Radar/SConscript')
SConscript('Constants/SConscript')
SConscript('XmlUtil/SConscript')
SConscript('Sensor/SConscript')
SConscript('Orbit/SConscript')
SConscript('Attitude/SConscript')
SConscript('Scene/SConscript')
SConscript('Planet/SConscript')
SConscript('Renderer/SConscript')
SConscript('Doppler/SConscript')
SConscript('Location/SConscript')
SConscript('Image/SConscript')
SConscript('Filter/SConscript')
SConscript('ImageFilter/SConscript')
SConscript('Catalog/SConscript')
SConscript('InsarProc/SConscript')
SConscript('Util/SConscript')
SConscript('Unwrap/SConscript')
SConscript('IsceProc/SConscript') ##KK, ML 2013-07-24: processors for isceApp.py
SConscript('Stack/SConscript') ##KK, ML 2013-07-24: get all selected scenes from xml
SConscript('Registry/SConscript')
SConscript('StripmapProc/SConscript')
SConscript('TopsProc/SConscript')
SConscript('RtcProc/SConscript')
SConscript('Alos2Proc/SConscript')
SConscript('Alos2burstProc/SConscript')
